--  run command from root directory: "mysql -u root < schema.sql"

CREATE DATABASE IF NOT EXISTS checkout;

USE checkout;

CREATE TABLE IF NOT EXISTS customers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) DEFAULT '' NOT NULL,
  email VARCHAR(30) DEFAULT '' NOT NULL,
  password VARCHAR(30) DEFAULT '' NOT NULL,
  address1 VARCHAR(20) DEFAULT '' NOT NULL,
  address2 VARCHAR(20) DEFAULT '' NOT NULL,
  city VARCHAR(20) DEFAULT '' NOT NULL,
  state VARCHAR(2) DEFAULT '' NOT NULL,
  zip VARCHAR(5) DEFAULT 0 NOT NULL,
  phone VARCHAR(11) DEFAULT 0 NOT NULL,
  cc_num VARCHAR(16) DEFAULT 0 NOT NULL,
  expiry_date VARCHAR(5) DEFAULT '' NOT NULL,
  cvv VARCHAR(4) DEFAULT '' NOT NULL,
  billing_zip VARCHAR(5) DEFAULT 0 NOT NULL
);

